### ISSUE TITLE
Peer dependencies update to include angular v14

### ISSUE THREAD

**Issue by krishna217** [eFaps/ngx-store#2]
npm error when tried to update to angular v14

`@efaps/ngx-store@4.2.0" has incorrect peer dependency "@angular/common@^11.0.0 || ^12.0.0|| ^13.0.0".
 @efaps/ngx-store@4.2.0" has incorrect peer dependency "@angular/core@^11.0.0 || ^12.0.0 || ^13.0.0".`

Thanks

**Comment by smurfy** [comment]
Lib seems to work with angular 14, but `npm install` / `npm ci` fails, especially on a clean npm cache.
Installation via `npm install --legacy-peer-deps` works but this still not really fixes the problem for CI builds.

So this should be fixable by just bumping the dependencies in package.json.
